export const members = [
  {
    id: "rohan",
    name: "Rohan",
    fullName: "Rohan Chandra Sen",
    mainSkill: "blockchain",
    domains: [
      "web dev",
      "frontend developer",
      "backend engineer",
      "blockchain dev",
      "rust enthusiast",
      "3d-designer",
      "UX dveloper",
    ],
    portfolio: "/",
  },
  {
    id: "ritankar",
    name: "Ritankar",
    fullName: "Ritankar Saha",
    mainSkill: "cloud",
    domains: [
      "web dev",
      "frontend developer",
      "backend engineer",
      "blockchain dev",
      "golang enthusiast",
    ],
    portfolio: "/",
  },
  {
    id: "om",
    name: "Om",
    fullName: "Om Thorat",
    mainSkill: "cybersec",
    domains: [
      "web dev",
      "frontend developer",
      "backend engineer",
      "blockchain dev",
      "rust enthusiast",
    ],
    portfolio: "/",
  },
]
